#%RAML 1.0
title: Undewater Object Detection RESTful API
baseUri: http://api.uod.ai
version: v1
protocols: [HTTP]

/detect:
  description: "Object detection Service"
  get:
    description: "Get detections for the image frame sent by the client"
    body:
      binary/octet-stream:
        description: "Byte streams of the image frame that will be used to feed the object detection model"
    responses:
      200:
        body:
          application/json:
            description: "A json response containing the model's detections"
